name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run SonarQube analysis
      uses: sumitmalik51/sonarqube@main
