name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1'

    - name: Set up SonarQube
      uses: sonarsource/sonarqube-action@master
      with:
        token: ${{ secrets.SONARQUBE_TOKEN }}
        scanner-version: '4.6.2'
        quality-gate-wait: true

    - name: Build and analyze
      run: |
        dotnet restore
        dotnet build
        dotnet sonarscanner begin /k:${{ secrets.SONARQUBE_TOKEN }} /d:sonar.login="${{ secrets.SONARQUBE_TOKEN }}" /d:sonar.host.url="http://localhost:9000"
        dotnet build
        dotnet test
        dotnet sonarscanner end /d:sonar.login="${{ secrets.SONARQUBE_TOKEN }}"
