name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set up SonarQube
      uses: sonarsource/sonarqube-action@master
      with:
        token: ${{ secrets.SONAR_TOKEN }}
        scanner-version: '4.6.2'
        quality-gate-wait: true

    - name: Build and analyze
      run: |
        pip install -r requirements.txt
        sonar-scanner \
          -Dsonar.projectKey=admin \
          -Dsonar.sources=. \
          -Dsonar.login="${{ secrets.SONAR_TOKEN }}" \
          -Dsonar.host.url="${{ secrets.SONAR_HOST_URL }}"
